Repository JSD-0423/frontend-final-1, pull requests merged in 2023-07, with the labels that each got.

#8 Create theme file
  src/index.jsx
  src/theme.js
Labels: for review

#9 Create titled list component
  src/components/index.js
  src/components/titledLists/.gitkeep
  src/components/titledLists/TitledList.jsx
Labels: for review

#12 Create Text Button Component
  src/components/textButton/.gitkeep
  src/components/textButton/TextButton.jsx
Labels: for review

#13 Hero Section and Carousel Components
  package.json
  src/assets/heroSection1.png
  src/assets/heroSection2.svg
  src/components/carousel/.gitkeep
  src/components/carousel/Carousel.jsx
  src/components/heroSection/HeroSection.jsx
  src/components/index.js
Labels: Done

#15 Hero Section and carousel are done
  package.json
  src/assets/heroSection1.png
  src/assets/heroSection2.svg
  src/components/carousel/.gitkeep
  src/components/carousel/Carousel.jsx
  src/components/heroSection/HeroSection.jsx
  src/components/index.js
Labels: Done

#16 Fix libraries conflict
  package-lock.json
  package.json
  src/components/carousel/Carousel.jsx
Labels: for review

#17 Setup router and Layout
  package-lock.json
  package.json
  src/App.jsx
  src/components/heroSection/HeroSection.jsx
  src/layout/.gitkeep
  src/layout/Layout.jsx
  src/pages/.gitkeep
  src/pages/Home.jsx
  src/pages/index.js
Labels: for review

#19 Create HandPicked Collections
  src/assets/bagsCollection2.png
  src/assets/glassesCollection4.png
  src/assets/perfumeCollections1.png
  src/assets/watchCoolection3.png
  src/components/cardsWrapperHeader/CardsWrapperHeader.jsx
  src/components/footer/Footer.jsx
  src/components/heroSection/HeroSection.jsx
  src/components/index.js
  src/components/socialIcon/SocialIcon.jsx
  src/components/titledImageCard/.gitkeep
  src/components/titledImageCard/TitledImageCard.jsx
  src/layout/Layout.jsx
  src/pages/Home.jsx
Labels: for review

#21 created filter based card component
  src/components/cardsWrapperHeader/CardsWrapperHeader.jsx
  src/components/customContainer/CustomContainer.jsx
  src/components/filterBasedCard/.gitkeep
  src/components/filterBasedCard/FilterBasedCard.jsx
  src/components/filterBasedCollection/FilterBasedCollecttion.jsx
  src/components/iconBtn/IconBtn.jsx
  src/components/newArrivals/NewArrivals.jsx
  src/pages/Home.jsx
Labels: fix-conflict

#22 Shop by brand component
  src/assets/BibaBrand.png
  src/assets/ChanelBrand.png
  src/assets/DolceBrand.png
  src/assets/HMBrand.png
  src/assets/PradaBrand.png
  src/assets/zaraBrand.png
  src/components/ImageCard/.gitkeep
  src/components/ImageCard/ImageCard.jsx
  src/components/cardsWrapperHeader/CardsWrapperHeader.jsx
  src/components/filterBasedCollection/FilterBasedCollection.jsx
  src/components/handPickedCollections/HandPickedCollections.jsx
  src/components/index.js
  src/components/newArrivals/NewArrivals.jsx
  src/components/shopByBrands/ShopByBrands.jsx
  src/pages/Home.jsx
Labels: for review

#23 Create product carousel
  src/components/index.js
  src/components/thumbsCarousel/ThumbsCarousel.jsx
  src/components/thumbsCarousel/style.module.css
Labels: for review

#24 Create quantity counter
  src/components/index.js
  src/components/quantityCounter/QuantityCounter.jsx
Labels: for review

#26 Create Tabs Component
  src/components/index.js
  src/components/productTabs/CustomPanel.jsx
  src/components/productTabs/ProductTabs.jsx
Labels: Done

#27 Fix Style for Home Page
  package-lock.json
  package.json
  public/index.html
  src/components/ImageCard/ImageCard.jsx
  src/components/cardItem/CardItem.jsx
  src/components/cardsWrapperHeader/CardsWrapperHeader.jsx
  src/components/collectionCard/CollectionCard.jsx
  src/components/filterBasedCard/FilterBasedCard.jsx
  src/components/filterBasedCollection/FilterBasedCollection.jsx
  src/components/footer/Footer.jsx
  src/components/handPickedCollections/HandPickedCollections.jsx
  src/components/header/Header.jsx
  src/components/heroSection/HeroSection.jsx
  src/components/iconBtn/IconBtn.jsx
  src/components/index.js
  src/components/navbar/Navbar.jsx
  src/components/newArrivals/NewArrivals.jsx
  src/components/titledImageCard/TitledImageCard.jsx
  src/components/titledLists/TitledList.jsx
  src/components/topCategories/TopCategories.jsx
  src/theme.js
Labels: for review

#29 created category page with product list and it's responsive
  package-lock.json
  package.json
  public/index.html
  src/App.jsx
  src/components/availablePrices/AvailablePrices.jsx
  src/components/cardItem/CardItem.jsx
  src/components/customBreadcrumbs/CustomBreadcrumbs.jsx
  src/components/customBreadcrumbs/CustomBreadcrumbs.module.css
  src/components/filterBasedCard/FilterBasedCard.jsx
  src/components/handPickedCollections/HandPickedCollections.jsx
  src/components/header/Header.jsx
  src/components/iconBtn/IconBtn.jsx
  src/components/index.js
  src/components/newArrivals/NewArrivals.jsx
  src/components/productListing/ProductListing.jsx
  src/components/topCategories/TopCategories.jsx
  src/context/.gitkeep
  src/context/BreadCrumbsContext.js
  src/index.jsx
  src/pages/Category.jsx
  src/pages/index.js
Labels: Done

#30 Cart popup
  src/components/alertSection/.gitkeep
  src/components/cardItem/CardItem.jsx
  src/components/cardsWrapperHeader/CardsWrapperHeader.jsx
  src/components/cartAppBar/CartAppBar.jsx
  src/components/cartPopup/CartPopup.jsx
  src/components/filterBasedCard/FilterBasedCard.jsx
  src/components/filterBasedCollection/FilterBasedCollection.jsx
  src/components/header/Header.jsx
  src/components/heroSection/HeroSection.jsx
  src/components/iconBtn/IconBtn.jsx
  src/components/index.js
  src/components/navbar/Navbar.jsx
  src/components/newArrivals/NewArrivals.jsx
  src/components/orderDetails/OrderDetails.jsx
  src/components/overlay/Overlay.jsx
  src/components/productDescription/ProductDescription.jsx
  src/components/productDetails/ProductDetails.jsx
  src/components/quantityCounter/QuantityCounter.jsx
  src/components/shopByBrands/ShopByBrands.jsx
  src/layout/Layout.jsx
Labels: Done

#31 API setup integration
  package-lock.json
  package.json
  src/API/.gitkeep
  src/API/API.js
  src/hooks/.gitkeep
  src/hooks/useAxiosFetch.jsx
Labels: for review

#33 Added pagination to ProductListing component.
  src/components/productListing/ProductListing.jsx
  src/components/productListing/productLists.js
Labels: Done

#35 Create cart page
  src/App.jsx
  src/Skeletons/Products.jsx
  src/components/cartOrders/CartOrders.jsx
  src/components/cartPopup/CartPopup.jsx
  src/components/index.js
  src/components/newArrivals/NewArrivals.jsx
  src/components/orderDetails/OrderDetails.jsx
  src/components/ordersTable/OrdersTable.jsx
  src/pages/Cart.jsx
  src/pages/Home.jsx
  src/pages/index.js
Labels: for review
